-- Unified Testing Schema for Oracle
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE operational_data';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

CREATE TABLE operational_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(36),
    action VARCHAR2(255),
    amount NUMBER(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO operational_data (user_id, action, amount) VALUES ('u1', 'purchase', 100.00);
INSERT INTO operational_data (user_id, action, amount) VALUES ('u1', 'sale', 50.00);
INSERT INTO operational_data (user_id, action, amount) VALUES ('u2', 'purchase', 200.00);
COMMIT;
